name: "Build new artifacts"

on:
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

env:
  REGISTRY: 294354037686.dkr.ecr.ap-northeast-1.amazonaws.com
  IMAGE: blockchain-klaytn
  DOCKERFILE: Dockerfile

jobs:
  build-artifacts:
    runs-on: [self-hosted, general]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Set env
        run: |
          echo "REVISION=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "COMMIT=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Build and push image
        run: |
          DOCKER_BUILDKIT=1 docker build -t ${REGISTRY}/${IMAGE}:${REVISION} -f ${DOCKERFILE} .
          docker push ${REGISTRY}/${IMAGE}:${REVISION}
          docker rmi ${REGISTRY}/${IMAGE}:${REVISION}
          docker run --name dryrun --rm ${REGISTRY}/${IMAGE}:${REVISION} ken version

      - name: Lark Notification
        continue-on-error: true
        run: |
          notiv3 "Blockchain klaytn latest image pushed 🎉" ${REGISTRY}/${IMAGE}:${REVISION}
